version: '2.1'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/db/data
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db/data:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

  hawk:
    build: .
    links:
      - mongodb
    container_name: hawk
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MONGODB_PORT=27017
      - MONGODB_SCHEMA=hawk
      - MONGODB_HOST=mongodb
      - LOG_LEVEL=DEBUG
    depends_on:
      - mongodb